### ISSUE TITLE
System Programing

### ISSUE THREAD

**Issue by RAJAASAD2723** [zakawat/System-Programing-BCS-7C#1]
salam bai....bai request hy ke ap ke codes me jidr {public double balance { get; set; } = 0; }hy....
is me bai get set ke sath equal zero hamary pas accept nai krta codes me....kindly ap ye check kren,,,,,
me ne 2 3 bar run kia hy lakin error resolve nai ho raha ,,,
ho sakta hy ke mery pas koi fault ho so kindly meri b rehnamayi kr de please

**Comment by zsubzwary** [comment]
@RAJAASAD2732 Error kis project k kis code me ha ...?

**Comment by RAJAASAD2723** [comment]
Bai jo Guess game lab task hy us me hy abi tk me ne jo check kia hy
... Ho sakta hy ke me wrong hun... Me just ap se xhexk krne ka keh raha hun
sir...

**Comment by zsubzwary** [comment]
@RAJAASAD2723  bhai ye batawo server side wale me ya client side wale me .,....???

**Comment by RAJAASAD2723** [comment]
Yr delegate and event ke ander b likha hwa hy... Bad me check kr lena...
Koi zarori nai bai abi.... Ap aram se check kr lena.. Bad me

**Comment by zsubzwary** [comment]
@RAJAASAD2723  jee link number bata du , our project ka name bata du !!

**Comment by zsubzwary** [comment]
@RAJAASAD2723  bhai ap is line ki baat kaar rahe hu ...?
`public int temp { get; set; } = 0;`
Jo k **Delegates and Events** wale project me ha ??

**Comment by RAJAASAD2723** [comment]
Jee bai

**Comment by zsubzwary** [comment]
Bhai main ne update kaar di ha, ap dobara download karo, ab wo masla haaal hu gaya ha !!

Dobara download karna . OKAY ??

**Comment by RAJAASAD2723** [comment]
Ok sir jee wesy kia masla tha

**Comment by zsubzwary** [comment]
Ap commit message parho gay tu apko pata chal jaye ga !!
Our code me bhi osi line k neeche likha howa ha k kiya issue tha !!
